apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "mongodb"
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.mongodb.persistence.storageClass }}
      storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mongodb.persistence.size | default "1Gi" }}
